### ISSUE TITLE
Enhancement : File -> instance 로 변환하는 기능 추가

### ISSUE THREAD

**Issue by FeFe2200** [innohack2021/HotSource#41]
# ISSUE
 File -> instance 로 변환하는 기능 추가

## 종류

- [ ] New Feature

## 내용
 File -> instance 로 변환하는 기능 추가

**Comment by 247programmers** [comment]
please retry.

1. change the directory name.

2. delete some trash method.

**Comment by 247programmers** [comment]
plz retry

**Comment by 247programmers** [comment]
plz retry
